pychen1025/amazon/urls.py
# coding=utf-8
# Author: weitingtao
# File: urls.py
# Create_time: 2019/10/19 19:56

from django.urls import path
from . import views


app_name = 'amazon'
urlpatterns = [
    path('home/', views.home, name='主页'),
    path('chart/', views.chart, name='折线图'),
    path('collect/<asin>', views.collect, name='收藏'),
    path('alibaba/<asin>', views.alibaba, name='1688'),
    path('monitor/<asin>', views.monitor, name='监测'),
    path('readInfo/<update_time>', views.readInfo, name='阅读进度'),
]

pychen1025/login/urls.py
# coding=utf-8
# Author: weitingtao
# File: urls.py.py
# Create_time: 2019/10/18 22:08

from django.urls import path, re_path
from . import views


app_name = 'pychen_login'
urlpatterns = [
    re_path(r'^login/$', views.pychen_login, name='pychen_login'),
]

pychen1025/pychen/urls.py
from django.contrib import admin
from django.urls import path, include
import login.urls
import amazon.urls
from login import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include(login.urls)),
    path('', views.pychen_login, name='pychen_login'),
    path('', include(amazon.urls)),
]

pychen1025/amazon/models.py
from django.db import models

# Create your models here.


class AsinInfo(models.Model):
    asin = models.CharField(primary_key=True, max_length=20)
    title = models.CharField(max_length=250, blank=True, null=True)
    brand = models.CharField(max_length=100, blank=True, null=True)
    merchant = models.CharField(max_length=20, blank=True, null=True)
    sellers = models.CharField(max_length=5, blank=True, null=True)
    img = models.CharField(max_length=200, blank=True, null=True)
    price = models.CharField(max_length=10, blank=True, null=True)
    rank = models.IntegerField(blank=True, null=True)
    review = models.CharField(max_length=10, blank=True, null=True)
    star = models.CharField(max_length=10, blank=True, null=True)
    delivery = models.CharField(max_length=32, blank=True, null=True)
    build_time = models.CharField(max_length=32, blank=True, null=True)
    update_time = models.CharField(max_length=32, blank=True, null=True)
    collection = models.CharField(max_length=1, blank=True, null=True)
    alibaba_link = models.CharField(max_length=200, blank=True, null=True)
    monitor = models.CharField(max_length=32, blank=True, null=True)
    readinfo = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'asin_info'


class GmMonitor(models.Model):
    asin = models.CharField(max_length=15, blank=True, null=True)
    update_time = models.CharField(primary_key=True, max_length=20)
    brand = models.CharField(max_length=30, blank=True, null=True)
    title = models.CharField(max_length=200, blank=True, null=True)
    img = models.CharField(max_length=200, blank=True, null=True)
    ranks = models.CharField(max_length=20, blank=True, null=True)
    price = models.CharField(max_length=20, blank=True, null=True)
    seller = models.CharField(max_length=20, blank=True, null=True)
    price1 = models.CharField(max_length=20, blank=True, null=True)
    seller1 = models.CharField(max_length=20, blank=True, null=True)
    registered = models.CharField(max_length=32, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'gm_monitor'

    # def __str__(self):
    #     return self.asin


class MonitorAsin(models.Model):
    asin = models.CharField(primary_key=True, max_length=32)
    update_time = models.CharField(max_length=32, blank=True, null=True)
    alibaba_link = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'monitor_asin'

pychen1025/amazon/views.py
from django.shortcuts import render, redirect
from .models import AsinInfo
from .models import GmMonitor
from .models import MonitorAsin
from django.http import HttpResponse
import django.utils.timezone as timezone
from django.contrib.auth.decorators import login_required


# Create your views here.
def collect(request, asin):
    # collection == 0不收藏collection == 1收藏
    a = AsinInfo.objects.get(asin=asin)
    a.collection = request.POST['collection']
    a.save()
    return HttpResponse('OK')


def alibaba(request, asin):
    # 1688链接统一放到需要监测的asin库monitor_asin中
    a = MonitorAsin.objects.get(asin=asin)
    a.alibaba_link = request.POST['1688']
    a.save()
    if request.POST['url'] == 'index':  # 如果是主页爬取的asin还需修改链接，用于home呈现链接
        # 货源链接存放在了2个数据库
        a = AsinInfo.objects.get(asin=asin)
        a.alibaba_link = request.POST['1688']
        a.save()
    return HttpResponse('OK')


def monitor(request, asin):
    # asin_info监测的asin和手动监测asin都存放在monitor_asin里面
    if request.POST['monitor'] == '取消监测':
        a = MonitorAsin.objects.get(asin=asin)
        a.delete()
        # 分辨不了哪个是手动添加的，取消监测
    elif request.POST['monitor'] == '开始监测':
        a = MonitorAsin.objects.create(asin=asin, update_time=timezone.now(), alibaba_link='0')
        a.save()
    return HttpResponse('OK')


def readInfo(request, update_time):
    # 只需要每个日期取出一个值用来存储阅读记录即可，遍历时只要有一个值就可以
    read_rows = request.POST['read_rows']
    a = AsinInfo.objects.filter(update_time__contains=update_time)[0]
    a.readinfo = read_rows
    a.save()
    return HttpResponse('OK')

@login_required
# 跟卖数据，交互的数据库为:amazon -> asin_info
def home(request):
    update_time = AsinInfo.objects.order_by('update_time').values_list('update_time')
    update_time = list(map(lambda x: x[0][:10], update_time))
    update_time = sorted(list(set(update_time)), reverse=True)
    print(update_time)
    asin_list = AsinInfo.objects.filter(update_time__contains=update_time[0]).order_by('rank')  # 默认取出最新一天找的跟卖
    if request.POST:
        asin_list = AsinInfo.objects.filter(update_time__contains=request.POST['date']).order_by('rank')
        if request.POST['collection'] == '已收藏的产品':
            asin_list = AsinInfo.objects.filter(collection='1').order_by('-rank')
            count = len(asin_list)
            content = {'跟卖listings': asin_list, '数据获取时间': update_time, '选择时间': request.POST['date'], '计数': count,
                       'collection': 1}
            return render(request, 'index.html', content)
        count = len(asin_list)
        content = {'跟卖listings': asin_list, '数据获取时间': update_time, '选择时间': request.POST['date'], '计数': count,
                   'collection': 0}
        return render(request, 'index.html', content)
    else:
        count = len(asin_list)
        content = {'跟卖listings': asin_list, '数据获取时间': update_time, '选择时间': update_time[0], '计数': count, 'collection': 0}
        return render(request, 'index.html', content)


@login_required
# 跟卖监测网页，交互的数据库为:amazon -> gm_monitor
def chart(request):
    # chart页面渲染需要用到两个数据库的信息，一个是gm_monitor的监测信息，一个是monitor_asin的阿里巴巴链接，
    # 可以将两个数据库信息的信息在views中加工到一起，去templates中变量计算很麻烦，因为监测asin是唯一的，顺序可以对上，所以合并到一起不难
    # 获取阿里巴巴链接信息，数据库为amazon->monitor_asin
    # 获取跟卖信息  ,数据库为amazon->monitor_asin
    asin_list = MonitorAsin.objects.values_list('asin')  # 默认取出所有的asin
    asin_list = list(map(lambda x: x[0], asin_list))  # 将QuerySet迭代转换成列表
    count = len(asin_list)
    gmMonitor = []
    a = 24  # 默认显示24小时
    if request.POST:
        if request.POST['time'] == '48小时':
            a = 48
        elif request.POST['time'] == '一周':
            a = 168
    for asin in asin_list:
        dict = {}
        asin_info = GmMonitor.objects.filter(asin=asin).order_by('-update_time')[:a]  # 每个asin最后24个值，代表24个小时
        alibaba_link = MonitorAsin.objects.filter(asin=asin).values_list('alibaba_link')[0][0]  # monitor_asin数据库的数据
        img = asin_info.values_list('img')
        img = list(map(lambda x: x[0], img))
        if len(img) == 0:
            continue
        else:
            img = img[0]
        brand = asin_info.values_list('brand')[0][0]
        rank = asin_info.values_list('ranks')[0][0]
        price = asin_info.values_list('price')[0][0]
        registered = asin_info.values_list('registered')[0][0]
        # 取出所有卖家
        sellers = asin_info.values_list('seller')
        sellers = list(map(lambda x: x[0], sellers))  # 将QuerySet迭代转换成列表
        sellers = list(set(sellers))  # sellers去重
        sellers = ','.join(sellers)
        dict['asin'] = asin
        dict['img'] = img
        dict['brand'] = brand
        dict['rank'] = rank
        dict['price'] = price
        dict['registered'] = registered
        dict['alibaba_link'] = alibaba_link
        dict['sellers'] = sellers
        # 判断品牌是否变化
        brand = asin_info.values_list('brand')
        brand = list(map(lambda x: x[0], brand))  # 将QuerySet迭代转换成列表
        brand = list(set(brand))  # sellers去重
        if len(brand) > 1:
            if 'null' not in brand:
                brand_change = 'YES'
        else:
            brand_change = 'NO'
        # 判断标题是否变化
        title = asin_info.values_list('title')
        title = list(map(lambda x: x[0], title))  # 将QuerySet迭代转换成列表
        title = list(set(title))  # sellers去重
        if len(title) > 1:
            if 'null' not in brand:
                title_change = 'YES'
        else:
            title_change = 'NO'
        # 判断图片是否变化
        img = asin_info.values_list('img')
        img = list(map(lambda x: x[0], img))  # 将QuerySet迭代转换成列表
        while 'null' in img:
            img.remove('null')
        img = list(map(lambda x: x.split('I/')[-1].split('.')[0], img))  # 过滤尺寸的变化
        img = list(set(img))  # sellers去重
        if len(img) > 1:
            img_change = 'YES'
        else:
            img_change = 'NO'
        dict['brand_change'] = brand_change
        dict['title_change'] = title_change
        dict['img_change'] = img_change
        # 时间坐标轴
        update_time = asin_info.values_list('update_time')
        update_time = list(map(lambda x: x[0][8:13].replace(' ', '-'), update_time))
        dict['li_time'] = list(reversed(update_time))
        gmMonitor.append(dict)
        ranks = asin_info.values_list('ranks')
        ranks = list(map(lambda x: x[0], ranks))
        seller = asin_info.values_list('seller')
        seller = list(map(lambda x: x[0], seller))
        price = asin_info.values_list('price')
        price = list(map(lambda x: x[0], price))
        seller1 = asin_info.values_list('seller1')
        seller1 = list(map(lambda x: x[0], seller1))
        price1 = asin_info.values_list('price1')
        price1 = list(map(lambda x: x[0], price1))
        y, p1, s1, P1, S1, P2, S2 = seller_match(update_time, ranks, seller, seller1, price, price1)
        dict['ranks'] = list(reversed(y))
        dict['p1'] = list(reversed(p1))
        dict['s1'] = s1
        dict['P1'] = list(reversed(P1))
        dict['S1'] = S1
        dict['P2'] = list(reversed(P2))
        dict['S2'] = S2
    content = {'data': gmMonitor, '计数': count}
    return render(request, 'hightchart.html', content)


def seller_match(times, ranks, sellers, seller1s, prices, price1s):
    x = times  # 时间列表
    y = ranks  # 排名列表
    s1 = sellers  # 购物车卖家
    s2 = seller1s  # 卖家2价格列表0
    p1 = prices  # 购物车价格列表
    p2 = price1s  # 卖家2
    li = []  # 按时间段来新建一个列表，每个时间段一个字典，包含 买家对应价格的键值对
    for i in range(len(x)):
        dict = {}
        dict[s1[i]] = p1[i]
        dict[s2[i]] = p2[i]
        li.append(dict)
    # print(li)
    seller_set = list(set(s1))
    # print(seller_set)
    P1 = []
    P2 = []
    if len(seller_set) == 1:  # 购物车一直是一个人的
        # print('购物车一直没变')
        P1 = p1
        P2 = p2
        S1 = seller_set[0]
        seller_set2 = list(set(s2))
        while 'null' in seller_set2:
            seller_set2.remove('null')
        if seller_set2:
            S2 = seller_set2[0]
        else:
            S2 = 'null'
    else:
        # print('有人跟卖')
        S1 = seller_set[0]
        S2 = seller_set[1]
        for i in li:
            if seller_set[0] in i:
                P1.append(i[seller_set[0]])
            else:
                P1.append(0)
            if seller_set[1] in i:
                P2.append(i[seller_set[1]])
            else:
                P2.append(0)
    # 将排名转换成数字
    for i in range(len(y)):
        y[i] = int(y[i])
    # 将价格转换成数字
    for i in range(len(p1)):
        p1[i] = float(p1[i])
    for i in range(len(P1)):
        P1[i] = float(P1[i])
    for i in range(len(P2)):
        P2[i] = float(P2[i])
    return y, p1, s1, P1, S1, P2, S2

pychen1025/amazon/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static 'icons/pychen.ico' %}" type="image/x-icon"/>
    <link rel="stylesheet" href="{% static 'css/bootstrap3.3.7.css' %}">
    <!-- <link rel="stylesheet" href="{% static 'css/bootstrap3.3.7.css' %}"> -->
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <script src="{% static 'js/jquery3.4.1.js' %}"></script>
    <script src="{% static 'js/bootstrap3.3.7.js' %}"></script>
    <title>@weitingtao</title>

<body>
<!-- Static navbar -->
<nav class="navbar navbar-fixed-top navbar-inverse" id="topNav">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <!--                style="margin: 0 0;padding: 0 0;" 解决图标不能居中-->
            <a class="navbar-brand" href="#" , style="margin: 0 0;padding: 0 0;">
                <img src="{% static 'images/pychen.png' %}" height="50" width="50" alt="logo"></a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li id="amazonData"><a href="{% url 'amazon:主页' %}">亚马逊数据</a></li>
                <li id="amazonMonitor"><a href="{% url 'amazon:折线图' %}">数据监测</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">亚马逊网址 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="https://www.amazon.com/Best-Sellers/zgbs/ref=zg_bsnr_tab" target="_blank">Best
                            Seller</a></li>
                        <li><a href="https://www.amazon.com/gp/new-releases/?ref_=nav_cs_newreleases" target="_blank">New
                            Release</a></li>
                        <li><a href="https://www.amazon.com/dp/" target="_blank">dp Link</a></li>
                    </ul>
                </li>
                <li><a href="#">About</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </div>
        <!--/.container-fluid -->
    </div>
</nav>
{% block 主体 %}
{% endblock 主体 %}
<footer style="height: 100px;background-color: #313641">
    <div class="container" style="width: 200px;padding-top: 20px;margin-right: 50px">
          <a id='scrollTop' href="#" style="color: white;font-size: large">返回顶部</a>
    </div>
</footer>
<script>
    $($('scrollTop').click(function () {
        window.scrollTo(0,0)
    }))
</script>
</body>
</html>

pychen1025/amazon/templates/hightchart.html
{% extends "base.html" %}
{% block 主体 %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/chart.css' %}">
<script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>
<script>$('#amazonMonitor').addClass('active')</script> /*选中导航栏加深颜色*/
<div id='nav_all' class="container-fluid" style="padding-top:80px;padding-bottom: 10px">
    <div class="col-md-2">
        <form class="form-inline" method="post" action="">{% csrf_token %}
            <div class="form-group">
                <span class="icon icon-time"></span>
                <label>Date：</label>
                <select name="time" class="form-control">
                    <option>24小时</option>
                    <option>48小时</option>
                    <option>一周</option>
                </select>
            </div>
            <button type="submit" class="btn btn-success">提交</button>
        </form>
    </div>
    <div class="col-md-2">
        <div class="form-inline">
            <span class="icon icon-house"></span>
            <label>Store：</label>
            <select id='store' name="store" class="form-control">
                <option>全部</option>
                <option>FF</option>
                <option>FY</option>
            </select>
            </div>
    </div>
    <div class="col-md-3 form-inline">
        <input name='1688' type="text" class="form-control" placeholder="手动添加Asin">
        <button id='addAsin' class="btn btn-default alibaba">Submit</button>
    </div>
</div>



<!-- Table -->
<table class="table table-responsive">
    <caption>共查询出<span id='count'>{{计数}}</span>条商品结果</caption>
    <thead>
    <tr class="table-dark">
        <th>#</th>
        <th>image</th>
        <th>Info</th>
        <th>priceChart</th>
        <th>rankChart</th>
    </tr>
    </thead>
    <tbody>
    {% for monitor in data %}
    <tr>
        <th scope="row" style="width:30px;">{{forloop.counter}}</th>
        <td style="width:300px; vertical-align:middle;">
            <a href="https://www.amazon.com/dp/{{monitor.asin}}" target="_blank">
                <img src="{{monitor.img}}" lazy="loaded" style="width: 300px; height: 300px;">
            </a>
            <button class="btn btn-danger post" style="margin-top: 5px; float: left; margin-left: 16px; width: 80px;"
                    name="{{ monitor.asin }}">
                取消监测
            </button>
            <div class='link' {% if monitor.alibaba_link == '0' %}style="display: none"{% endif %}>
                <a  href="{{monitor.alibaba_link}}" target="_blank">
                    <button class="btn btn-primary" type="button"
                            style="margin-top: 5px; float: left; margin-left: 16px; width: 80px;">
                        <span>货源链接</span>
                    </button>
                </a>
                <span class="link1688" style="margin-top: 35px">{{monitor.alibaba_link}}</span>
            </div>
        </td>
        <td style="width: 300px; height: 300px;margin: auto;">
            <h4>Asin : <span class="label label-default">{{monitor.asin}}</span></h4>
            <h4>Rank : <span class="label label-success"># {{monitor.rank}}</span></h4>
            <h4>Price : <span class="label label-info">$ {{monitor.price}}</span></h4>
            <h4>BuyBox : <span class="label label-info seller">{{monitor.sellers}}</span></h4>
            <h4>Brand : <span class="label label-info">{{monitor.brand}}</span></h4>
            <h4>Registered : <span class="label label-danger">{{monitor.registered}}</span></h4>
            <h4>图片是否变化 ： <span class="label label-warning">{{monitor.img_change}}</span></h4>
            <h4>标题是否变化 ： <span class="label label-warning">{{monitor.title_change}}</span></h4>
            <h4>品牌是否变化 ： <span class="label label-warning">{{monitor.brand_change}}</span></h4>
            <div class="form-inline">
                <input name='1688' type="text" class="form-control" placeholder="1688货源" style="width:170px">
                <button class="btn btn-default alibaba" name="{{monitor.asin}}">Submit</button>
            </div>
        </td>
        <td>
            <div id='{{monitor.asin}}1' style="min-width: 310px; height: 320px; margin: 0 auto; width: 640px;"></div>
        </td>
        <td>
            <div id='{{monitor.asin}}2' style="min-width: 310px; height: 320px; margin: 0 auto; width: 640px;"></div>
        </td>
        <script type="text/javascript">
            Highcharts.chart('{{monitor.asin}}1', {
                chart: {
                    backgroundColor:'#bebec8',
                    type: 'line'
                },
                title: {
                    text: '{{monitor.asin}} 的价格折线图'
                },
                subtitle: {
                    text: '{{monitor.asin}}'
                },
                xAxis: {
                    categories: [
                        {% for module in monitor.li_time %}
                            "{{module}}",
                        {% endfor %}
                    ]
                },
                yAxis: {
                    title: {
                        text: '$ price'
                    }
                },
                plotOptions: {
                    line: {
                        dataLabels: {
                            enabled: true
                        },
                        enableMouseTracking: true
                    }
                },
                series: [{
                    name: 'buybox',
                    data: {{monitor.p1}}
                }, {
                    name: '{{monitor.S1}}',
                    data: {{monitor.P1}}
                },
            {
                    name: '{{monitor.S2}}',
                    data:  {{monitor.P2}}
                }]
            });
        </script>
        <script type="text/javascript">
            Highcharts.chart('{{monitor.asin}}2', {
                chart: {
                    backgroundColor:'#d2d2dc',
                    type: 'line'
                },
                title: {
                    text: '{{monitor.asin}} 的排名折线图'
                },
                subtitle: {
                    text: '{{monitor.asin}}'
                },
                xAxis: {
                    categories: [
                         {% for module in monitor.li_time %}
                            "{{module}}",
                        {% endfor %}
                    ]
                },
                yAxis: {
                    title: {
                        text: '# Rank'
                    }
                },
                plotOptions: {
                    line: {
                        dataLabels: {
                            enabled: true
                        },
                        enableMouseTracking: true
                    }
                },
                series: [{
                    name: 'Rank',
                    data: {{monitor.ranks}}
                }]
            });
        </script>
    </tr>
    {% endfor %}
    </tbody>
</table>
<script>
    $($('#store').change(function () {
        if ($('#store').val() == 'FF') {
            console.log('FF')
            $('.seller').parent().parent().parent().show()
            var a = $('.seller:not(:contains("fayfairy"))');
            for (let i = 0; i < a.length; i++) {
                $(a[i]).parent().parent().parent().hide()
            }
            var other = a.length
             console.log(other + '不个包含ff的个数')
            var num1 = {{计数}}-other
            console.log(num1)
            $('#count').text(num1)
        }
        if ($('#store').val() == 'FY') {
            console.log('FY')
            $('.seller').parent().parent().parent().show()
            var b = $('.seller:not(:contains("FAYE MALL"))');
            for (let i = 0; i < b.length; i++) {
                $(b[i]).parent().parent().parent().hide()
            }
            var other = b.length
            console.log(other + '个不包含fy的个数')
            var num2 = {{计数}}-other
            console.log(num2)
             $('#count').text(num2)
        }
            if ($('#store').val() == '全部') {
            console.log('全部')
            $('.seller').parent().parent().parent().show()
            var num3 = {{计数}}
            console.log(num3)
             $('#count').text(num3)
        }
    }))
    $.ajaxSetup({ data: { csrfmiddlewaretoken: '{{ csrf_token }}' } });
    $($('.post').click(function () {
      var num4 = {{计数}}-1
        console.log(num4)
         $('#count').text(num4)
        $(this).parent().parent().hide()
        url = '/monitor/' + $(this).attr('name')
            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    'monitor':'取消监测'
                },
                success: function () {
                    console.log('取消监测')
                },
            })
        }))
    $($('#addAsin').click(function () {
        var asin = $('input[name="1688"]').val()
        if(asin.length != 10 || asin.substring(0,2) != 'B0'){
            alert('请输入正确的asin!')
        }else{
            url = '/monitor/' + asin
            $.ajax({
                type: 'POST',
                url: url,
                data: {
                    'monitor': '开始监测',
                    'action':'手动添加'
                },
                success: function () {
                    console.log('开始监测')
                   alert('添加成功')
                },
            })
         $('input[name="1688"]').val('')
        }
        }))
    $($('.alibaba').click(function () {
        var url_1688 = '/alibaba/' + $(this).attr('name')
        link = $(this).prev().val()
        if(link == '0'){
            $(this).parent().parent().prev().find('div.link').hide()
        }else{
        $(this).parent().parent().prev().find('div a').attr('href',link)
        $(this).parent().parent().prev().find('div span.link1688').text(link)
         $(this).parent().parent().prev().find('div.link').show()}
        $.ajax({
            type: 'POST',
            url: url_1688,
            data: {
                '1688': link,
                'url': 'chart'
            },
            success: function () {
                console.log(link)
            },
        })
    }))
</script>

{% endblock 主体 %}

pychen1025/amazon/templates/test.html
<!DOCTYPE HTML>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Highcharts Example</title>

		<style type="text/css">

		</style>
	</head>
	<body>
<script src="http://cdn.highcharts.com.cn/highcharts/highcharts.js"></script>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>



		<script type="text/javascript">
Highcharts.chart('container', {
    chart: {
        type: 'line'
    },
    title: {
        text: 'Monthly Average Temperature'
    },
    subtitle: {
        text: 'Source: WorldClimate.com'
    },
    xAxis: {
        categories: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
    },
    yAxis: {
        title: {
            text: 'Temperature (°C)'
        }
    },
    plotOptions: {
        line: {
            dataLabels: {
                enabled: true
            },
            enableMouseTracking: false
        }
    },
    series: [{
        name: 'Tokyo',
        data: [7.0, 6.9, 9.5, 14.5, 18.4, 21.5, 25.2, 26.5, 23.3, 18.3, 13.9, 9.6]
    }, {
        name: 'London',
        data: [3.9, 4.2, 5.7, 8.5, 11.9, 15.2, 17.0, 16.6, 14.2, 10.3, 6.6, 4.8]
    }]
});
		</script>
	</body>
</html>